name: dental_camera_s700c_plugin_example
description: "Demonstrates how to use the dental_camera_s700c_plugin plugin."
publish_to: 'none' 

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  dental_camera_s700c_plugin:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
