name: dental_camera_s700c_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  gallery_saver: ^2.3.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  screen_recorder: ^0.2.0
  image: ^3.0.1
  flutter_ffmpeg: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.dental_camera_s700c_plugin
        pluginClass: DentalCameraS700cPlugin
      ios:
        pluginClass: DentalCameraS700cPlugin
