name: dental_camera_s700c_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  gal: ^2.3.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  screen_recorder: ^0.2.0
  #ffmpeg_kit_flutter: ^6.0.3
  flutter_quick_video_encoder: ^1.6.0

  open_settings_plus: ^0.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  


  plugin:
    platforms:
      android:
        package: com.example.dental_camera_s700c_plugin
        pluginClass: DentalCameraS700cPlugin
      ios:
        pluginClass: DentalCameraS700cPlugin
